### PR TITLE
yaml: android: zero `rpmbemul` and `misc` partitions

### PR DESCRIPTION
**Pull request by rshym**
Signed-off-by: Ruslan Shymkevych <ruslan_shymkevych@epam.com>

### CODE REVIEW

**Comment by lorc** [comment]
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

But I'd like @arminn to take a look at this.

**Comment by rshym** [comment]
I have added an increment of the minimal version of the moulin, to reflect the required changes.

**Comment by rshym** [comment]
For proper work, this PR now needs https://github.com/xen-troops/moulin/pull/59 to be merged.

**Comment by arminn** [comment]
LGTM

**Comment by rshym** [comment]
Ack's are added.
Ready to be merged.

**Pull request merged**
