### PR TITLE
Dev/vladyslav goncharuk/virtio integration V2

### PR DESCRIPTION
**Pull request by otyshchenko1**
All comments provided for V1 (https://github.com/xen-troops/meta-xt-prod-devel-rcar/pull/107) were addressed. Rebased on recent master and runtime tested with DomU (w/ and w/o virtio) and compile tested with DomA (w/ virtio only).

### CODE REVIEW

**Comment by otyshchenko1** [comment]
Please note, related PR is at https://github.com/xen-troops/android_device_epam_xenvm-trout/pull/2

**Review by lorc — APPROVED** [review]
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by otyshchenko1** [comment]
Updated, added A-b to all patches and the following diff to the last commit (based on the clean build with Android + DDK prebuit)
```
otyshchenko@EPUAKYIW03DD:~/work/moulin-devel/prod-devel-virtio/yocto/meta-xt-prod-devel-rcar$ git diff
diff --git a/prod-devel-rcar-virtio.yaml b/prod-devel-rcar-virtio.yaml
index ef33e5b..1d1f895 100644
--- a/prod-devel-rcar-virtio.yaml
+++ b/prod-devel-rcar-virtio.yaml
@@ -536,6 +536,10 @@ parameters:
                 # Android uses DTB generated by DomD
                 doma: "%{YOCTOS_WORK_DIR}/%{DOMD_BUILD_DIR}/tmp/deploy/images/%{DOMD_MACHINE}/"
           domd:
+            sources:
+              - type: git
+                url: "https://github.com/kraj/meta-clang.git"
+                rev: kirkstone
             builder:
               layers:
                 - "../meta-clang"
```

**Comment by otyshchenko1** [comment]
> Please note, related PR is at [xen-troops/android_device_epam_xenvm-trout#2](https://github.com/xen-troops/android_device_epam_xenvm-trout/pull/2)

this one is already merged, so waiting for the last check with Android at the runtime before merging.

**Comment by lorc** [comment]
Okay. Could you please notify me when it will be ready to be merged?

**Comment by otyshchenko1** [comment]
> Okay. Could you please notify me when it will be ready to be merged?

Sure, I am waiting for the confirmation from Vladyslav Goncharuk, basically Android has started, there is something to re-check with vsock.

**Comment by otyshchenko1** [comment]
> Okay. Could you please notify me when it will be ready to be merged?

Yes, I and Vladyslav Goncharuk (@svlad-90) now think it is ready to be merged.

**Pull request merged**
