### PR TITLE
Changes zephyr section

### PR DESCRIPTION
**Pull request by dsemenets**
Change in zephyr section according to moulin version 0.13

### CODE REVIEW

**Comment by lorc** [comment]
Hi @dsemenets , 

Have you tested this change?

**Comment by dsemenets** [comment]
Yes. I will do more tests today.

**Comment by lorc** [comment]
Could you please elaborate commit description a bit more?
It would be nice to tell why exactly you are changing paths for zephyr.

**Comment by dsemenets** [comment]
Hi @lorc ,
I have successfully tested this changes

**Comment by lorc** [comment]
Great. Thank you.

`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Pull request merged**
