### PR TITLE
Add `meta-renesas` to the list of sources of `domu`

### PR DESCRIPTION
**Pull request by rshym**

### CODE REVIEW

**Comment by lorc** [comment]
Well, I don't think that Dom0 should depend on `meta-renesas`. So, I think it is better to add this layer only to DomU

**Comment by rshym** [comment]
Thanks for pointing, I was inattentive and didn't notice this important thing.
Commit is reworked:
- meta-renesas is added to domu's sources
- no modifications are done to COMMON_SOURCES
- commit message is reworked to reflect new change

Fix is checked running `ninja conf-dom*` for all three components (dom0, domd, dom) in 'clean' folder, to make sure that all required sources are fetched for each component.

**Comment by lorc** [comment]
`Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by rshym** [comment]
Reviewer is added. Ready to be merged.

**Pull request merged**
