### PR TITLE
Align the quoting of revisions in yaml files.

### PR DESCRIPTION
**Pull request by rshym**

### CODE REVIEW

**Comment by rshym** [comment]
Smoke-tested by the command `moulin prod-devel-rcarXXX.yaml` for each modified file.

**Comment by rshym** [comment]
Off-site comments regarding commit messages are addressed.

**Review by lorc — APPROVED** [review]
`Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by rshym** [comment]
Force-pushed just due to reformat of the "Fixes:"-field in the first commit, according to the recommendations.

**Pull request merged**
