### PR TITLE
dom0: Modifications of doma.service

### PR DESCRIPTION
**Pull request by rshym**
- dom0: Use drop-in for doma.service
- dom0: Add dependency on sndbe and displbe for doma.service 

---
Need to be merged AFTER https://github.com/xen-troops/meta-xt-common/pull/20

### CODE REVIEW

**Comment by rshym** [comment]
Tested by build of prod-devel-rcar for h3ulcb-4x2g-kf together with https://github.com/xen-troops/meta-xt-common/pull/20.
Works as expected:
```
root@generic-armv8-xt-dom0:~# systemctl list-dependencies --no-pager doma                                                                                     
doma.service
* |-backend-ready@bridge.service
* |-backend-ready@displbe.service
* |-backend-ready@sndbe.service
```
And `systemctl status doma`:
```
* doma.service - Android VM
     Loaded: loaded (/lib/systemd/system/doma.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/doma.service.d
             `-doma-backends.conf, doma-set-root.conf
```

**Comment by rshym** [comment]
To be honest, I'm not sure that this is a good idea to name the drop-in file `doma-backend.conf`, so I' am open to good proposals.

**Comment by lorc** [comment]
> To be honest, I'm not sure that this is a good idea to name the drop-in file doma-backend.conf, so I' am open to good proposals.

Well, taking into account that it resides in `doma.service.d` you can name it just `backends.conf`.

`Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by rshym** [comment]
RB is added.
`doma-backend.conf` is renamed to `backends.conf`. I have checked that renamed file is placed into `/etc/systemd/system/doma.service.d`.

Ready to be merged.

**Comment by rshym** [comment]
Re-pushed due to missed RB on the first commit.
Ready to be merged.

**Comment by rshym** [comment]
Re-pushed due to missed RB on the first commit.
Ready to be merged.

**Pull request merged**
