### PR TITLE
Miscellaneous changes to yamls

### PR DESCRIPTION
**Pull request by rshym**
- add ../../ to common_data path
- use separate MACHINE for each domain 
- remove poky's default layers

### CODE REVIEW

**Comment by otyshchenko1** [comment]
First and last commit - `Reviewed-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>`
With https://github.com/xen-troops/meta-xt-prod-devel-rcar/pull/112/commits/eb318eb94bc3bac7583bd8373d36ba4065f2b799 applied, some hard-coded names are still present (I noticed for generic-armv8-xt and xenvm). Or this is by intention?

**Review by lorc — COMMENTED** [review]
Should you do the same for agl.yaml?

**Comment by rshym** [comment]
RB is added to the first and the last commits.
Instances of the `generic-armv8-xt` are replaced with `DOM0_MACHINE` (in devel and virtio files).
agl-related yaml is updated accordingly.

**Comment by rshym** [comment]
Rebased to the latest master branch.

**Review by lorc — APPROVED** [review]
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by rshym** [comment]
PR was successfully built on the local host with the following commands:
```
moulin prod-devel-rcar.yaml --MACHINE h3ulcb-4x2g --ENABLE_DOMU yes
ninja full.img
```

**Comment by lorc** [comment]
Looks like there are conflicts after the last merge. Could you please fix them?

**Comment by rshym** [comment]
Rebased on the latest master branch. Conflicts are solved.

**Pull request merged**
