### PR TITLE
domd: Append sndbe and camerabe to IMAGE_INSTALL

### PR DESCRIPTION
**Pull request by rshym**

### CODE REVIEW

**Comment by lorc** [comment]
Not sure that this is the correct approach. We don't need `sndbe` or any other back-end if there are no guests that require that back-end.

So it is more

**Comment by lorc** [comment]
Sorry. That was huge missclick :)

I wanted to cancel my comment, but instead clicked on "close with comment"

**Comment by rshym** [comment]
So, you think it's better to add something like `sound` in DISTRO_FEATURES? Just like we already have `pvcamera` and `vis`?

**Comment by lorc** [comment]
> So, you think it's better to add something like sound in DISTRO_FEATURES? 

Well, if you wish, you can reuse an existing DISTRO_FEATURE (`alsa` or `pulseaudio` maybe?). But I'd prefer to not add new ones.

Besides, whole idea of our "product" is to have some known set of features that we are supporting. So I'm thinking it is better to limit "configurability" of  the product. I.e. are there any changes that we might want prod-devel without sound enabled?

**Comment by rshym** [comment]
Successfully tested with https://github.com/xen-troops/meta-xt-common/pull/28 on h3ulcb-4x2g-kf.

**Comment by rshym** [comment]
RB is added.
Successfully tested.
Ready to be merged.

**Pull request merged**
